x = 5 + 3;
y = x - 4;
z = 3*3;
p = "a";
s = "b";
if(z > y) then
	if(p > s) then
		print("a > b");
	else
		print("a <= b");
	fi
	print("z greater than y "::"WOOOOOO");
else
	print("h"::"i"::" "::"t"::"h"::"e"::"r"::"e");
fi


print("about to try out a while loop!");

counter = 0;
while(counter < 5) do
	print(counter);
	counter = counter + 1;
ob


print("finished while loop!");


print("here's a while loop to find gcd of:");

x = 138;
y = 12;
print(x);
print("and");
print(y);

r = x % y;
gcd = y;
while(r != 0) do
	tmp = x / y;
	x = y;
	y = r;
	gcd = y;
	r = x % y;
ob
print("is ");
print(gcd);
